<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EspaiderJuizosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $espaiderJuizos = [
            ["Juizado de Apoio ao Superendividado de Salvador","da Vara do Sistema dos Juizados Especiais de apoio ao superendividado da Comarca de Salvador/BA","JEC Apoio ao Superendividado Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["10ª Vara SJE Consumidor de Salvador - Vespertino","da 10ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","10ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["11ª Vara SJE Consumidor de Salvador - Matutino","da 11ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","11ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["12ª Vara SJE Consumidor de Salvador - Vespertino","da 12ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","12ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["13ª Vara SJE Consumidor de Salvador - Matutino","da 13ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","13ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["14ª Vara SJE Consumidor de Salvador - Vespertino","da 14ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","14ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["15ª Vara SJE Consumidor de Salvador - Matutino","da 15ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","15ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["16ª Vara SJE Consumidor de Salvador - Vespertino","da 16ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","16ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["17ª Vara SJE Consumidor de Salvador - Matutino","da 17ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","17ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["18ª Vara SJE Consumidor de Salvador - Vespertino","da 18ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","18ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["19ª Vara SJE Consumidor de Salvador - Matutino","da 19ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","19ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["20ª Vara SJE Consumidor de Salvador - Vespertino","da 20ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","20ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Barreiras","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Barreiras/BA","1ª JEC Barreiras","Barreiras","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Camaçari","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Camaçari/BA","1ª JEC Camaçari","Camaçari","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Eunápolis","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Eunápolis/BA","1ª JEC Eunápolis","Eunápolis","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Feira de Santana","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Feira de Santana/BA","1ª JEC Feira de Santana","Feira de Santana","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Guanambi","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Guanambi/BA","1ª JEC Guanambi","Guanambi","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Ilhéus","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Ilhéus/BA","1ª JEC Ilhéus","Ilhéus","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Irecê","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Irecê/BA","1ª JEC Irecê","Irecê","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Itabuna - Vespertino","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Itabuna/BA","1ª JEC Itabuna","Itabuna","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Itapetinga","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Itapetinga/BA","1ª JEC Itapetinga","Itapetinga","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Jacobina","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Jacobina/BA","1ª JEC Jacobina","Jacobina","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Jequié","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Jequié/BA","1ª JEC Jequié","Jequié","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Juazeiro","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Juazeiro/BA","1ª JEC Juazeiro","Juazeiro","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Lauro de Freitas","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Lauro de Freitas/BA","1ª JEC Lauro de Freitas","Lauro de Freitas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Paulo Afonso","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Paulo Afonso/BA","1ª JEC Paulo Afonso","Paulo Afonso","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Porto Seguro","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Porto Seguro/BA","1ª JEC Porto Seguro","Porto Seguro","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Serrinha","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Serrinha/BA","1ª JEC Serrinha","Serrinha","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Vitória da Conquista","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Vitória da Conquista/BA","1ª JEC Vitória da Conquista","Vitória da Conquista","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Teixeira de Freitas","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Teixeira de Freitas/BA","1ª JEC Teixeira de Freitas","Teixeira de Freitas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE de Simões Filho","da 1ª Vara do Sistema dos Juizados Especiais da comarca de Simões Filho/BA","1ª JEC Simões Filho","Simões Filho","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE Consumidor de Salvador - Matutino","da 1ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da comarca de Salvador/BA","1ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE Causas Comuns de Salvador - Matutino","da 1ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","1ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara SJE Trânsito de Salvador - Matutino","da 1ª Vara do Sistema dos Juizados Especiais de Trânsito da comarca de Salvador/BA","1ª JEC Trânsito Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE Trânsito de Salvador - Vespertino","da 2ª Vara do Sistema dos Juizados Especiais de Trânsito da comarca de Salvador/BA","2ª JEC Trânsito Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE Trânsito de Salvador - Vespertino","da 3ª Vara do Sistema dos Juizados Especiais de Trânsito da comarca de Salvador/BA","3ª JEC Trânsito Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Barreiras","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Barreiras/BA","2ª JEC Barreiras","Barreiras","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Camaçari","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Camaçari/BA","2ª JEC Camaçari","Camaçari","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Eunápolis","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Eunápolis/BA","2ª JEC Eunápolis","Eunápolis","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Feira de Santana","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Feira de Santana/BA","2ª JEC Feira de Santana","Feira de Santana","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Ilhéus","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Ilhéus/BA","2ª JEC Ilhéus","Ilhéus","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Irecê","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Irecê/BA","2ª JEC Irecê","Irecê","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Itabuna","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Itabuna/BA","2ª JEC Itabuna","Itabuna","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Jacobina","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Jacobina/BA","2ª JEC Jacobina","Jacobina","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Jequié","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Jequié/BA","2ª JEC Jequié","Jequié","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Juazeiro","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Juazeiro/BA","2ª JEC Juazeiro","Juazeiro","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Lauro de Freitas","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Lauro de Freitas/BA","2ª JEC Lauro de Freitas","Lauro de Freitas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Paulo Afonso","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Paulo Afonso/BA","2ª JEC Paulo Afonso","Paulo Afonso","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Porto Seguro","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Porto Seguro/BA","2ª JEC Porto Seguro","Porto Seguro","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Serrinha","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Serrinha/BA","2ª JEC Serrinha","Serrinha","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Teixeira de Freitas","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Teixeira de Freitas/BA","2ª JEC Teixeira de Freitas","Teixeira de Freitas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE de Vitória da Conquista","da 2ª Vara do Sistema dos Juizados Especiais da comarca de Vitória da Conquista/BA","2ª JEC Vitória da Conquista","Vitória da Conquista","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE Causas Comuns de Salvador - Vespertino","da 2ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","2ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["2ª Vara SJE Consumidor de Salvador - Vespertino","da 2ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","2ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE de Feira de Santana","da 3ª Vara do Sistema dos Juizados Especiais da comarca de Feira de Santana/BA","3ª JEC Feira de Santana","Feira de Santana","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE de Ilhéus","da 3ª Vara do Sistema dos Juizados Especiais da comarca de Ilhéus/BA","3ª JEC Ilhéus","Ilhéus","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE de Itabuna","da 3ª Vara do Sistema dos Juizados Especiais da comarca de Itabuna/BA","3ª JEC Itabuna","Itabuna","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE de Vitória da Conquista","da 3ª Vara do Sistema dos Juizados Especiais da comarca de Vitória da Conquista/BA","3ª JEC Vitória da Conquista","Vitória da Conquista","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE Causas Comuns de Salvador - Matutino","da 3ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","3ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["3ª Vara SJE Consumidor de Salvador - Matutino","da 3ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","3ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["4ª Vara SJE Causas Comuns de Salvador - Vespertino","da 4ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","4ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["4ª Vara SJE Consumidor de Salvador - Vespertino","da 4ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","4ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["4ª Vara SJE de Feira de Santana","da 4ª Vara do Sistema dos Juizados Especiais da comarca de Feira de Santana/BA","4ª JEC Feira de Santana","Feira de Santana","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["5ª Vara SJE Causas Comuns de Salvador - Matutino","da 5ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","5ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["5ª Vara SJE Consumidor de Salvador - Matutino","da 5ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","5ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["6ª Vara SJE Causas Comuns de Salvador - Vespertino","da 6ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","6ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["6ª Vara SJE Consumidor de Salvador - Vespertino","da 6ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","6ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["7ª Vara SJE Causas Comuns de Salvador - Matutino","da 7ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","7ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["7ª Vara SJE Consumidor de Salvador - Matutino","da 7ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","7ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["8ª Vara SJE Causas Comuns de Salvador - Vespertino","da 8ª Vara do Sistema dos Juizados Especiais de Causas Comuns da comarca de Salvador/BA","8ª JEC Causas Comuns Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["8ª Vara SJE Consumidor de Salvador - Vespertino","da 8ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","8ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["9ª Vara SJE Consumidor de Salvador - Matutino","da 9ª Vara do Sistema dos Juizados Especiais de Defesa do Consumidor da Comarca de Salvador/BA","9ª JEC Consumo Salvador","Salvador","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível e Criminal de Riachão do Jacuípe","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Riachão do Jacuípe/BA","JEC Riachão do Jacuípe","Riachão do Jacuípe","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível de Cícero Dantas","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Cícero Dantas/BA","JEC Cícero Dantas","Cícero Dantas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível de Itamaraju","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Itamaraju/BA","JEC Itamaraju","Itamaraju","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível de Santa Maria da Vitória","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Santa Maria da Vitória/BA","JEC Santa Maria da Vitória","Santa Maria da Vitória","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível e Criminal de Brumado","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Brumado/BA","JEC Brumado","Brumado","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível e Criminal de Coaraci","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Coaraci/BA","JEC Coaraci","Coaraci","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível e Criminal de Ipiaú","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Ipiaú/BA","JEC Ipiaú","Ipiaú","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE Cível e Criminal de Ipirá","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Ipirá/BA","JEC Ipirá","Ipirá","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Alagoinhas","da Vara do Sistema dos Juizados Especiais da comarca de Alagoinhas/BA","JEC Alagoinhas","Alagoinhas","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Bom Jesus da Lapa","da Vara do Sistema dos Juizados Especiais Cíveis e Criminais da comarca de Bom Jesus da Lapa/BA","JEC Bom Jesus da Lapa","Bom Jesus da Lapa","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Canavieiras","da Vara do Sistema dos Juizados Especiais da comarca de Canavieiras/BA","JEC Canavieiras","Canavieiras","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Conceição do Coité","da Vara do Sistema dos Juizados Especiais da comarca de Conceição do Coité/BA","JEC Conceição do Coité","Conceição do Coité","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Euclides da Cunha","da Vara do Sistema dos Juizados Especiais da comarca de Euclides da Cunha/BA","JEC Euclides da Cunha","Euclides da Cunha","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Gandu","da Vara do Sistema dos Juizados Especiais da comarca de Gandu/BA","JEC Gandu","Gandu","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Itaberaba","da Vara do Sistema dos Juizados Especiais da comarca de Itaberaba/BA","JEC Itaberaba","Itaberaba","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Livramento de Nossa Senhora","da Vara do Sistema dos Juizados Especiais da comarca de Livramento de Nossa Senhora/BA","JEC Livramento Nossa Senhora","Livramento de Nossa Senhora","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Luís Eduardo Magalhães","da Vara do Sistema dos Juizados Especiais da comarca de Luís Eduardo Magalhães/BA","JEC Luís Eduardo Magalhães","Luís Eduardo Magalhães","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Santo Estêvão","da Vara do Sistema dos Juizados Especiais da comarca de Santo Estêvão/BA","JEC Santo Estêvão","Santo Estêvão","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Senhor do Bonfim","da Vara do Sistema dos Juizados Especiais da comarca de Senhor do Bonfim/BA","JEC Senhor do Bonfim","Senhor do Bonfim","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Valença","da Vara do Sistema dos Juizados Especiais da comarca de Valença/BA","JEC Valença","Valença","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["Vara SJE de Santo Antônio de Jesus","da Vara do Sistema dos Juizados Especiais da comarca de Santo Antônio de Jesus/BA","JEC Santo Antônio de Jesus","Santo Antônio de Jesus","TJ/BA - Varas dos Sistemas dos Juizados Especiais"],
            ["1ª Vara de Consumo de Salvador","da 1ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","1ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["2ª Vara de Consumo de Salvador","da 2ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","2ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["3ª Vara de Consumo de Salvador","da 3ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","3ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["4ª Vara de Consumo de Salvador","da 4ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","4ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["5ª Vara de Consumo de Salvador","da 5ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","5ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["6ª Vara de Consumo de Salvador","da 6ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","6ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["7ª Vara de Consumo de Salvador","da 7ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","7ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["8ª Vara de Consumo de Salvador","da 8ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","8ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["9ª Vara de Consumo de Salvador","da 9ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","9ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["10ª Vara de Consumo de Salvador","da 10ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","10ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["11ª Vara de Consumo de Salvador","da 11ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","11ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["12ª Vara de Consumo de Salvador","da 12ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","12ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["13ª Vara de Consumo de Salvador","da 13ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","13ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["14ª Vara de Consumo de Salvador","da 14ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","14ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["15ª Vara de Consumo de Salvador","da 15ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","15ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["16ª Vara de Consumo de Salvador","da 16ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","16ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["17ª Vara de Consumo de Salvador","da 17ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","17ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["18ª Vara de Consumo de Salvador","da 18ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","18ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["19ª Vara de Consumo de Salvador","da 19ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","19ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["20ª Vara de Consumo de Salvador","da 20ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","20ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["21ª Vara de Consumo de Salvador","da 21ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","21ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["22ª Vara de Consumo de Salvador","da 22ª Vara dos Feitos Relativos às Relações de Consumo da comarca de Salvador/BA","22ª Vara Consumo Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["1ª Vara Cível e Comercial de Salvador","da 1ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","1ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["2ª Vara Cível e Comercial de Salvador","da 2ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","2ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["3ª Vara Cível e Comercial de Salvador","da 3ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","3ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["4ª Vara Cível e Comercial de Salvador","da 4ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","4ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["5ª Vara Cível e Comercial de Salvador","da 5ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","5ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["6ª Vara Cível e Comercial de Salvador","da 6ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","6ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["7ª Vara Cível e Comercial de Salvador","da 7ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","7ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["8ª Vara Cível e Comercial de Salvador","da 8ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","8ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["9ª Vara Cível e Comercial de Salvador","da 9ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","9ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["10ª Vara Cível e Comercial de Salvador","da 10ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","10ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["11ª Vara Cível e Comercial de Salvador","da 11ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","11ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["12ª Vara Cível e Comercial de Salvador","da 12ª Vara dos Feitos Cíveis e Comerciais da comarca de Salvador/BA","12ª Vara Cível e Comercial Salvador","Salvador","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["1ª Vara Cível de Lauro de Freitas","da 1ª Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Lauro de Freitas/BA","1ª Vara Consumo, Cível e Comercial Lauro de Freitas","Lauro de Freitas","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["2ª Vara Cível de Lauro de Freitas","da 2ª Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Lauro de Freitas/BA","2ª Vara Consumo, Cível e Comercial Lauro de Freitas","Lauro de Freitas","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Amélia Rodrigues","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Amélia Rodrigues/BA","Vara Consumo, Cível e Comercial Amélia Rodrigues","Amélia Rodrigues","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Conceição do Jacuípe","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Conceição do Jacuípe/BA","Vara Consumo, Cível e Comercial Conceição do Jacuípe","Conceição do Jacuípe","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Entre Rios","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Entre Rios/BA","Vara Consumo, Cível e Comercial Entre Rios","Entre Rios","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Ibotirama","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Ibotirama/BA","Vara Consumo, Cível e Comercial Ibotirama","Ibotirama","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Iaçu","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Iaçu/BA","Vara Consumo, Cível e Comercial Iaçu","Iaçu","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Itapicuru","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Itapicuru/BA","Vara Consumo, Cível e Comercial Itapicuru","Itapicuru","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Mata de São João","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Mata de São João/BA","Vara Consumo, Cível e Comercial Mata de São João","Mata de São João","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Paripiranga","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Paripiranga/BA","Vara Consumo, Cível e Comercial Paripiranga","Paripiranga","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Queimadas","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Queimadas/BA","Vara Consumo, Cível e Comercial Queimadas","Queimadas","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Ribeira do Pombal","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Ribeira do Pombal/BA","Vara Consumo, Cível e Comercial Ribeira do Pombal","Ribeira do Pombal","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Santa Bárbara","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Santa Bárbara/BA","Vara Consumo, Cível e Comercial  Santa Bárbara","Santa Bárbara","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Saúde","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Saúde/BA","Vara Consumo, Cível e Comercial Saúde","Saúde","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["Vara Cível de Uauá","da Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Uauá/BA","Vara Consumo, Cível e Comercial Uauá","Uauá","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"],
            ["2ª Vara Cível de Guanambi","da 2ª Vara dos Feitos Relativos às Relações de Consumo, Cíveis e Comerciais da comarca de Guanambi/BA","2ª Vara de Consumo, Cível e Comercial Guanambi","Guanambi","TJ/BA - Varas de Consumo, Cíveis, Comerciais, Criminais e varas únicas"]            ,
        ];

        $paramsInsert = [];
        foreach($espaiderJuizos as $juizo) {
            $arr["nome_juizo_espaider"] = $juizo[0];
            $arr["redacao_cabecalho_juizo"] = $juizo[1];
            $arr["redacao_resumida_juizo"] = $juizo[2];
            $arr["espaider_comarca_id"] = DB::table("espaider_comarcas")->where("nome_comarca_espaider", $juizo[3])->value("id");
            $arr["espaider_orgao_id"] = DB::table("espaider_orgaos")->where("nome_orgao_espaider", $juizo[4])->value("id");
            $paramsInsert[] = $arr;
        }

        DB::table('espaider_juizos')->insert($paramsInsert);
    }
}
