<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SistemasJudJuizosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $sisjudJuizos = [
            ["1º Juizado Cível de Defesa do Consumidor - UNIVERSO - VESPERTINO","1ª Vara SJE Consumidor de Salvador - Matutino"],
            ["Juizado Especial Cível de Apoio ao Superendividado","Juizado de Apoio ao Superendividado de Salvador"],
            ["1ª VSJE DE CAUSAS COMUNS (MATUTINO)","1ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["1ª VSJE DE CAUSAS COMUNS (LIBERDADE MATUTINO)","1ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["1ª VSJE DE TRÂNSITO (DETRAN MATUTINO)","1ª Vara SJE Trânsito de Salvador - Matutino"],
            ["2ª VSJE DE TRÂNSITO (VESPERTINO)","2ª Vara SJE Trânsito de Salvador - Vespertino"],
            ["1ª VSJE DE TRÂNSITO (DETRAN VESPERTINO)","3ª Vara SJE Trânsito de Salvador - Vespertino"],
            ["1ª VSJE DO CONSUMIDOR (MATUTINO)","1ª Vara SJE Consumidor de Salvador - Matutino"],
            ["1ª VSJE DO CONSUMIDOR (IMBUÍ MATUTINO)","1ª Vara SJE Consumidor de Salvador - Matutino"],
            ["2ª VSJE DE CAUSAS COMUNS (VESPERTINO)","2ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["2ª VSJE DE CAUSAS COMUNS (LIBERDADE VESPERTINO)","2ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["2ª VSJE DO CONSUMIDOR (IMBUÍ VESPERTINO)","2ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["2º Juizado Cível de Defesa do Consumidor - BROTAS - VESPERTINO","2ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["2ª VSJE DO CONSUMIDOR (VESPERTINO)","2ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["3ª VSJE DE CAUSAS COMUNS (PIATÃ MATUTINO)","3ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["3ª VSJE DE CAUSAS COMUNS (MATUTINO)","3ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["3ª VSJE DO CONSUMIDOR (IMBUÍ MATUTINO)","3ª Vara SJE Consumidor de Salvador - Matutino"],
            ["4ª VSJE DE CAUSAS COMUNS (VESPERTINO)","4ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["3ª VSJE DO CONSUMIDOR (MATUTINO)","3ª Vara SJE Consumidor de Salvador - Matutino"],
            ["4ª VSJE DE CAUSAS COMUNS (PIATÃ VESPERTINO)","4ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["4ª VSJE DO CONSUMIDOR (VESPERTINO)","4ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["4ª VSJE DO CONSUMIDOR (IMBUÍ VESPERTINO)","4ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["5ª VSJE DE CAUSAS COMUNS (MATUTINO)","5ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["5ª VSJE DE CAUSAS COMUNS (BONFIM MATUTINO)","5ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["5ª VSJE DO CONSUMIDOR (MATUTINO)","5ª Vara SJE Consumidor de Salvador - Matutino"],
            ["5ª VSJE DO CONSUMIDOR (IMBUÍ MATUTINO)","5ª Vara SJE Consumidor de Salvador - Matutino"],
            ["6ª VSJE DE CAUSAS COMUNS (VESPERTINO)","6ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["6ª VSJE DE CAUSAS COMUNS (BONFIM VESPERTINO)","6ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["6ª VSJE DO CONSUMIDOR (VESPERTINO)","6ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["7ª VSJE DO CONSUMIDOR (MATUTINO)","7ª Vara SJE Consumidor de Salvador - Matutino"],
            ["6ª VSJE DO CONSUMIDOR (IMBUÍ VESPERTINO)","6ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["7ª VSJE DE CAUSAS COMUNS (MATUTINO)","7ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["7ª VSJE DE CAUSAS COMUNS (IMBUÍ MATUTINO)","7ª Vara SJE Causas Comuns de Salvador - Matutino"],
            ["7ª VSJE DO CONSUMIDOR (RUY BARBOSA MATUTINO)","7ª Vara SJE Consumidor de Salvador - Matutino"],
            ["8ª VSJE DE CAUSAS COMUNS (VESPERTINO)","8ª Vara SJE Causas Comuns de Salvador - Vespertino"],
            ["8ª VSJE DO CONSUMIDOR (VESPERTINO)","8ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["8ª VSJE DO CONSUMIDOR (RUY BARBOSA VESPERTINO)","8ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["9ª VSJE DO CONSUMIDOR (RUY BARBOSA MATUTINO)","9ª Vara SJE Consumidor de Salvador - Matutino"],
            ["9ª VSJE DO CONSUMIDOR (MATUTINO)","9ª Vara SJE Consumidor de Salvador - Matutino"],
            ["10ª VSJE DO CONSUMIDOR (VESPERTINO)","10ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["10ª VSJE DO CONSUMIDOR (RUY BARBOSA VESPERTINO)","10ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["Juizado Modelo Cível - Ext. Jorge Amado - VESPERTINO","10ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["11ª VSJE DO CONSUMIDOR (MATUTINO)","11ª Vara SJE Consumidor de Salvador - Matutino"],
            ["11ª VSJE DO CONSUMIDOR (FEDERAÇÃO MATUTINO)","11ª Vara SJE Consumidor de Salvador - Matutino"],
            ["12ª VSJE DO CONSUMIDOR (FEDERAÇÃO VESPERTINO)","12ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["12ª VSJE DO CONSUMIDOR (VESPERTINO)","12ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["13ª VSJE DO CONSUMIDOR (MATUTINO)","13ª Vara SJE Consumidor de Salvador - Matutino"],
            ["13ª VSJE DO CONSUMIDOR (FEDERAÇÃO MATUTINO)","13ª Vara SJE Consumidor de Salvador - Matutino"],
            ["14ª VSJE DO CONSUMIDOR (VESPERTINO)","14ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["14ª VSJE DO CONSUMIDOR (FEDERAÇÃO VESPERTINO)","14ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["15ª VSJE DO CONSUMIDOR (MATUTINO)","15ª Vara SJE Consumidor de Salvador - Matutino"],
            ["15ª VSJE DO CONSUMIDOR (UNIVERSO MATUTINO)","15ª Vara SJE Consumidor de Salvador - Matutino"],
            ["16ª VSJE DO CONSUMIDOR (VESPERTINO)","16ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["16ª VSJE DO CONSUMIDOR (UNIVERSO VESPERTINO)","16ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["17ª VSJE DO CONSUMIDOR (MATUTINO)","17ª Vara SJE Consumidor de Salvador - Matutino"],
            ["17ª VSJE DO CONSUMIDOR (UNIVERSO MATUTINO)","17ª Vara SJE Consumidor de Salvador - Matutino"],
            ["18ª VSJE DO CONSUMIDOR (VESPERTINO)","18ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["18ª VSJE DO CONSUMIDOR (UNIVERSO VESPERTINO)","18ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["1ª VSJE DE TRÂNSITO (MATUTINO)","1ª Vara SJE Trânsito de Salvador - Matutino"],
            ["19ª VSJE DO CONSUMIDOR (MATUTINO)","19ª Vara SJE Consumidor de Salvador - Matutino"],
            ["20ª VSJE DO CONSUMIDOR (VESPERTINO)","20ª Vara SJE Consumidor de Salvador - Vespertino"],
            ["1ª Vara do Sistema dos Juizados - BARREIRAS","1ª Vara SJE de Barreiras"],
            ["2ª Vara do Sistema dos Juizados - BARREIRAS","2ª Vara SJE de Barreiras"],
            ["1ª Vara do Sistema dos Juizados - CAMAÇARI","1ª Vara SJE de Camaçari"],
            ["2ª Vara do Sistema Juizados - CONCEIÇÃO DO COITÉ","Vara SJE de Conceição do Coité"],
            ["1ª Vara do Sistema Juizados - CONCEIÇÃO DO COITÉ","Vara SJE de Conceição do Coité"],
            ["1ª Vara do Sistema dos Juizados - EUNÁPOLIS","1ª Vara SJE de Eunápolis"],
            ["2ª Vara do Sistema dos Juizados - EUNÁPOLIS","2ª Vara SJE de Eunápolis"],
            ["Vara do Sistema dos Juizados - SERRINHA","1ª Vara SJE de Serrinha"],
            ["1ª Vara do Sistema dos Juizados - SERRINHA","1ª Vara SJE de Serrinha"],
            ["1ª Vara do Sistema dos Juizados - FEIRA DE SANTANA","1ª Vara SJE de Feira de Santana"],
            ["1ª Vara do Sistema dos Juizados - GUANAMBI","1ª Vara SJE de Guanambi"],
            ["1ª Vara do Sistema dos Juizados - ILHÉUS","1ª Vara SJE de Ilhéus"],
            ["1ª Vara do Sistema dos Juizados - IRECÊ","1ª Vara SJE de Irecê"],
            ["1ª Vara do Sistema dos Juizados - ITABUNA (VESP)","1ª Vara SJE de Itabuna - Vespertino"],
            ["1ª Vara do Sistema dos Juizados - ITAPETINGA","1ª Vara SJE de Itapetinga"],
            ["1ª Vara do Sistema dos Juizados - JACOBINA","1ª Vara SJE de Jacobina"],
            ["1ª Vara do Sistema dos Juizados - JEQUIÉ","1ª Vara SJE de Jequié"],
            ["1ª Vara do Sistema dos Juizados - JUAZEIRO","1ª Vara SJE de Juazeiro"],
            ["1ª Vara do Sistema dos Juizados - LAURO DE FREITAS","1ª Vara SJE de Lauro de Freitas"],
            ["2ª Vara do Sistema dos Juizados - PAULO AFONSO","2ª Vara SJE de Paulo Afonso"],
            ["1ª Vara do Sistema dos Juizados - PAULO AFONSO","1ª Vara SJE de Paulo Afonso"],
            ["1ª Vara do Sistema dos Juizados - PORTO SEGURO","1ª Vara SJE de Porto Seguro"],
            ["1ª Vara do Sistema dos Juizados- VIT. DA CONQUISTA","1ª Vara SJE de Vitória da Conquista"],
            ["1ª Vara do Sistema Juizados - Teixeira de Freitas","1ª Vara SJE de Teixeira de Freitas"],
            ["1ª Vara Juizados Especiais de Teixeira de Freitas","1ª Vara SJE de Teixeira de Freitas"],
            ["1ª Vara Sistema Juizados Especiais - Simões Filho","1ª Vara SJE de Simões Filho"],
            ["2ª Vara do Sistema dos Juizados - JACOBINA","2ª Vara SJE de Jacobina"],
            ["2ª Vara do Sistema dos Juizados - CAMAÇARI","2ª Vara SJE de Camaçari"],
            ["2ª Vara do Sistema dos Juizados - FEIRA DE SANTANA","2ª Vara SJE de Feira de Santana"],
            ["2ª Vara do Sistema dos Juizados - ILHÉUS","2ª Vara SJE de Ilhéus"],
            ["2ª Vara do Sistema dos Juizados - IRECÊ","2ª Vara SJE de Irecê"],
            ["2ª Vara do Sistema dos Juizados - ITABUNA (MAT)","2ª Vara SJE de Itabuna"],
            ["2ª Vara do Sistema dos Juizados - JEQUIÉ","2ª Vara SJE de Jequié"],
            ["2ª Vara do Sistema dos Juizados - JUAZEIRO","2ª Vara SJE de Juazeiro"],
            ["2ª Vara do Sistema dos Juizados - LAURO DE FREITAS","2ª Vara SJE de Lauro de Freitas"],
            ["2ª Vara do Sistema dos Juizados - PORTO SEGURO","2ª Vara SJE de Porto Seguro"],
            ["2ª Vara do Sistema dos Juizados - SERRINHA","2ª Vara SJE de Serrinha"],
            ["2ª Vara do Sistema dos Juizados- VIT. DA CONQUISTA","2ª Vara SJE de Vitória da Conquista"],
            ["2ª Vara do Sistema Juizados - Teixeira de Freitas","2ª Vara SJE de Teixeira de Freitas"],
            ["2ª Vara Juizados Especiais de Teixeira de Freitas","2ª Vara SJE de Teixeira de Freitas"],
            ["3ª Vara do Sistema dos Juizados - FEIRA DE SANTANA","3ª Vara SJE de Feira de Santana"],
            ["3ª Vara do Sistema dos Juizados - ILHÉUS","3ª Vara SJE de Ilhéus"],
            ["3ª Vara do Sistema dos Juizados - ITABUNA (MAT)","3ª Vara SJE de Itabuna"],
            ["3ª Vara do Sistema dos Juizados- VIT. DA CONQUISTA","3ª Vara SJE de Vitória da Conquista"],
            ["4ª Vara do Sistema dos Juizados - FEIRA DE SANTANA","4ª Vara SJE de Feira de Santana"],
            ["Vara do Sistema dos Juizados - BOM JESUS DA LAPA","Vara SJE de Bom Jesus da Lapa"],
            ["Juizado Esp. Cível e Criminal - BOM JESUS DA LAPA","Vara SJE de Bom Jesus da Lapa"],
            ["Juizado Esp. Cível e Criminal - RIACHÃO DO JACUÍPE","Vara SJE Cível e Criminal de Riachão do Jacuípe"],
            ["Vara do Sistema dos Juizados - RIACHÃO DO JACUÍPE","Vara SJE Cível e Criminal de Riachão do Jacuípe"],
            ["Juizado Especial Cível e Criminal - CÍCERO DANTAS","Vara SJE Cível de Cícero Dantas"],
            ["Juizado Especial Cível - ITAMARAJU","Vara SJE Cível de Itamaraju"],
            ["Juiz. Esp. Cível e Criminal-SANTA MARIA DA VITÓRIA","Vara SJE Cível de Santa Maria da Vitória"],
            ["Juizado Especial Cível - SANTA MARIA DA VITÓRIA","Vara SJE Cível de Santa Maria da Vitória"],
            ["Vara do Sistema dos Juizados - BRUMADO","Vara SJE Cível e Criminal de Brumado"],
            ["Juizado Especial Cível e Criminal - BRUMADO","Vara SJE Cível e Criminal de Brumado"],
            ["Juizado Especial Adjunto Cível/Criminal - COARACI","Vara SJE Cível e Criminal de Coaraci"],
            ["Juizado Especial Cível e Criminal - COARACI","Vara SJE Cível e Criminal de Coaraci"],
            ["Vara do Sistema dos Juizados - IPIAÚ","Vara SJE Cível e Criminal de Ipiaú"],
            ["Juizado Especial Cível e Criminal - IPIAÚ","Vara SJE Cível e Criminal de Ipiaú"],
            ["Juizado Especial Cível e Criminal - IPIRÁ","Vara SJE Cível e Criminal de Ipirá"],
            ["Vara do Sistema dos Juizados - IPIRÁ","Vara SJE Cível e Criminal de Ipirá"],
            ["Vara do Sistema dos Juizados - ALAGOINHAS","Vara SJE de Alagoinhas"],
            ["Vara do Sistema dos Juizados - CÍCERO DANTAS","Vara SJE Cível de Cícero Dantas"],
            ["Vara do Sistema dos Juizados - CANAVIEIRAS","Vara SJE de Canavieiras"],
            ["Vara do Sistema dos Juizados - CONCEIÇÃO DO COITÉ","Vara SJE de Conceição do Coité"],
            ["Vara do Sistema dos Juizados - EUCLIDES DA CUNHA","Vara SJE de Euclides da Cunha"],
            ["Vara do Sistema dos Juizados - GANDU","Vara SJE de Gandu"],
            ["Vara do Sist. dos Juizados - GANDU","Vara SJE de Gandu"],
            ["Vara do Sistema dos Juizados - ITABERABA","Vara SJE de Itaberaba"],
            ["Vara do Sistema dos Juizados - LUIS EDUARDO MAGALHÃES","Vara SJE de Luis Eduardo Magalhães"],
            ["Vara do Sist dos Juizados - Luís Eduardo Magalhães","Vara SJE de Luis Eduardo Magalhães"],
            ["Vara do Sistema dos Juizados - SANTO ESTEVÃO","Vara SJE de Santo Estêvão"],
            ["Vara do Sistema dos Juizados - SENHOR DO BONFIM","Vara SJE de Senhor do Bonfim"],
            ["Vara do Sistema dos Juizados - VALENÇA","Vara SJE de Valença"],
            ["Vara do Sistema dos Juizados-STO ANTÔNIO DE JESUS","Vara SJE de Santo Antônio de Jesus"],
            ["Vara do Sistema dos Juizados - ITAMARAJU","Vara SJE Cível de Itamaraju"],
            ["Vara do Sist dos Juizados - LIVRAMENTO DE N SRA","Vara SJE de Livramento de Nossa Senhora"],
            ["1ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","1ª Vara de Consumo de Salvador"],
            ["2ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","2ª Vara de Consumo de Salvador"],
            ["3ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","3ª Vara de Consumo de Salvador"],
            ["4ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","4ª Vara de Consumo de Salvador"],
            ["5ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","5ª Vara de Consumo de Salvador"],
            ["6ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","6ª Vara de Consumo de Salvador"],
            ["7ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","7ª Vara de Consumo de Salvador"],
            ["8ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","8ª Vara de Consumo de Salvador"],
            ["9ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","9ª Vara de Consumo de Salvador"],
            ["10ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","10ª Vara de Consumo de Salvador"],
            ["11ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","11ª Vara de Consumo de Salvador"],
            ["12ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","12ª Vara de Consumo de Salvador"],
            ["13ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","13ª Vara de Consumo de Salvador"],
            ["14ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","14ª Vara de Consumo de Salvador"],
            ["15ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","15ª Vara de Consumo de Salvador"],
            ["16ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","16ª Vara de Consumo de Salvador"],
            ["17ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","17ª Vara de Consumo de Salvador"],
            ["18ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","18ª Vara de Consumo de Salvador"],
            ["19ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","19ª Vara de Consumo de Salvador"],
            ["20ª VARA DE RELAÇÕES DE CONSUMO DA COMARCA DE SALVADOR","20ª Vara de Consumo de Salvador"],
        ];
        
        $paramsInsert = [];
        foreach($sisjudJuizos as $juizo) {
            $arr["nome_juizo_sistemas_jud"] = $juizo[0];
            $arr["espaider_juizo_id"] = DB::table("espaider_juizos")->where("nome_juizo_espaider", $juizo[1])->value("id");
            $paramsInsert[] = $arr;
        }

        DB::table('sistemas_jud_juizos')->insert($paramsInsert);
    }
}
